/**
 * Generates omp-native task-agent definitions from the Claude-format atlas
 * agent sources.
 *
 * Why: omp discards the frontmatter `model` of Claude-dialect plugin agents
 * (task/discovery.ts sets `ignoreModel` for plugins that declare the Claude
 * format, e.g. via `.claude-plugin/plugin.json`), so the copies under
 * `plugins/atlas/agents/` run on the session's default model. omp scans
 * `<extension-root>/agents` for extension packages and KEEPS `model` +
 * `thinkingLevel` there, and extension-package agents precede Claude plugin
 * agents in the first-wins-by-name merge — so generated omp-native copies in
 * this package override the model-less Claude copies of the same names.
 *
 * Usage (from any cwd): bun plugins/atlas/omp/gen-agents.ts
 * Reads   plugins/atlas/agents/*.md   (name, description, body)
 * Writes  plugins/atlas/omp/agents/<name>.md  (committed; idempotent)
 *
 * The parent re-runs this after the Claude-dialect agent bodies change.
 */
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import * as path from "node:path";
import { YAML } from "bun";
import { ATLAS_AGENT_NAMES, ATLAS_THINKING_LEVELS, modelPatternsFor, roleFor } from "./atlas-agents";

export interface GenerateOptions {
	/** Directory containing Claude-format atlas agent `*.md` sources. */
	agentsDir: string;
	/** Directory receiving generated omp-native agent `*.md` files. */
	outDir: string;
}

const HEADER = (sourceFile: string) => [
	"# GENERATED by omp/gen-agents.ts from agents/" + sourceFile + " — do not edit by hand.",
	"# Re-generate with: bun plugins/atlas/omp/gen-agents.ts (idempotent; commit the output).",
];

/** Split an agent markdown file into its frontmatter map and verbatim body. */
function parseAgentMarkdown(content: string): { frontmatter: Record<string, unknown>; body: string } {
	const trimmed = content.replace(/^\uFEFF/, "");
	if (!trimmed.startsWith("---")) throw new Error("agent file has no frontmatter");
	const closeIndex = trimmed.indexOf("\n---", 3);
	if (closeIndex < 0) throw new Error("agent file frontmatter is not closed");
	const frontmatter = YAML.parse(trimmed.slice(3, closeIndex)) as Record<string, unknown>;
	if (!frontmatter || typeof frontmatter !== "object") throw new Error("agent frontmatter did not parse to a map");
	const afterClose = trimmed.slice(closeIndex + 4);
	const body = afterClose.startsWith("\n") ? afterClose.slice(1) : afterClose;
	return { frontmatter, body };
}

/** Render one generated agent file for a parsed source agent. */
export function renderGeneratedAgent(sourceFile: string, content: string): string | null {
	const { frontmatter, body } = parseAgentMarkdown(content);
	const name = frontmatter.name;
	const description = frontmatter.description;
	if (typeof name !== "string" || !name.trim() || typeof description !== "string" || !description.trim()) {
		return null;
	}
	const thinkingLevel = ATLAS_THINKING_LEVELS[name];
	if (!thinkingLevel) {
		throw new Error("no thinkingLevel mapping for atlas agent " + name);
	}
	// JSON.stringify output is valid YAML (double-quoted scalar), so
	// descriptions containing colons/quotes stay safe without a YAML emitter.
	const lines = [
		"---",
		...HEADER(sourceFile),
		`name: ${JSON.stringify(name)}`,
		`description: ${JSON.stringify(description)}`,
		`thinkingLevel: ${thinkingLevel}`,
		`model: ${JSON.stringify(modelPatternsFor(name))}`,
		"# Lead-only dispatch: atlas workers must not spawn subagents.",
		`spawns: ${JSON.stringify("none")}`,
		"---",
		"",
		body,
	];
	return lines.join("\n").replace(/\n*$/, "\n");
}

/**
 * Generate every omp-native agent file. Writes only when the rendered bytes
 * differ from what is on disk, so re-running produces no diff.
 */
export function generateAgents({ agentsDir, outDir }: GenerateOptions): { written: string[] } {
	const sources = readdirSync(agentsDir)
		.filter(file => file.endsWith(".md"))
		.sort();
	const written: string[] = [];
	for (const sourceFile of sources) {
		const rendered = renderGeneratedAgent(sourceFile, readFileSync(path.join(agentsDir, sourceFile), "utf8"));
		if (rendered === null) continue;
		if (!statSync(outDir, { throwIfNoEntry: false })) mkdirSync(outDir, { recursive: true });
		const outPath = path.join(outDir, sourceFile);
		const existing = statSync(outPath, { throwIfNoEntry: false })
			? readFileSync(outPath, "utf8")
			: undefined;
		if (existing !== rendered) {
			writeFileSync(outPath, rendered);
			written.push(path.basename(sourceFile));
		}
	}
	return { written };
}

function main(): void {
	const agentsDir = path.resolve(import.meta.dir, "..", "agents");
	const outDir = path.resolve(import.meta.dir, "agents");
	const { written } = generateAgents({ agentsDir, outDir });
	if (written.length > 0) {
		console.log(`generated ${written.length} omp agent file(s): ${written.join(", ")}`);
	} else {
		console.log(`omp agent files up to date (${readdirSync(outDir).filter(f => f.endsWith(".md")).length} files)`);
	}
}

if (import.meta.main) main();

// Re-exported for tests and tooling that need the shared maps without
// importing the generator's side-effectful module graph.
export { ATLAS_AGENT_NAMES, ATLAS_THINKING_LEVELS, modelPatternsFor, roleFor };