import { expect, test } from "bun:test";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import * as path from "node:path";
import { YAML } from "bun";
import {
	ATLAS_AGENT_NAMES,
	ATLAS_AGENT_TARGETABLE,
	ATLAS_DEFAULT_FALLBACK_ROLE,
	ATLAS_MECHANIC_ROLE,
	ATLAS_THINKING_LEVELS,
	ATLAS_TIER_DEFAULTS,
	modelPatternsFor,
	roleFor,
	SMOL_FALLBACK_ROLE,
} from "./atlas-agents";
import { generateAgents, ompBody, renderGeneratedAgent } from "./gen-agents";

const agentsDir = path.resolve(import.meta.dir, "..", "agents");
const outDir = path.resolve(import.meta.dir, "agents");

function claudeAgentSources(): Record<string, string> {
	const sources: Record<string, string> = {};
	for (const file of readdirSync(agentsDir).filter(file => file.endsWith(".md"))) {
		const content = readFileSync(path.join(agentsDir, file), "utf8");
		const name = YAML.parse(content.slice(content.indexOf("---") + 3, content.indexOf("\n---", 4))).name;
		sources[name] = content;
	}
	return sources;
}

function generatedAgents(): Record<string, string> {
	const files: Record<string, string> = {};
	for (const file of readdirSync(outDir).filter(file => file.endsWith(".md"))) {
		files[file.replace(/\.md$/, "")] = readFileSync(path.join(outDir, file), "utf8");
	}
	return files;
}

function frontmatterOf(content: string): Record<string, unknown> {
	return YAML.parse(content.slice(content.indexOf("---") + 3, content.indexOf("\n---", 4))) as Record<string, unknown>;
}

function expectedModelChain(name: string, source: string): string[] {
	if (parseSource(source).frontmatter.model === "haiku") return [ATLAS_MECHANIC_ROLE, ATLAS_TIER_DEFAULTS.mechanic, SMOL_FALLBACK_ROLE];
	if (["verifier", "completeness-critic", "rls-privilege-audit"].includes(name)) {
		return [roleFor(name), ATLAS_DEFAULT_FALLBACK_ROLE, ATLAS_TIER_DEFAULTS.verifier, SMOL_FALLBACK_ROLE];
	}
	return [roleFor(name), ATLAS_TIER_DEFAULTS.worker, SMOL_FALLBACK_ROLE];
}

function expectAgentMatches(name: string, source: string, generatedContent: string): void {
	const { frontmatter, body } = parseSource(source);
	const fm = frontmatterOf(generatedContent);
	expect(fm.name).toBe(name);
	expect(fm.description).toBe(frontmatter.description);
	expect(fm.thinkingLevel).toBe(ATLAS_THINKING_LEVELS[name]);
	const model = fm.model as string[];
	expect(model[0]).toBe(roleFor(name));
	expect(model).toEqual(modelPatternsFor(name));
	expect(model).toEqual(expectedModelChain(name, source));
	expect(fm.spawns).toBe("none");
	expect(generatedContent.endsWith(ompBody(body)) || generatedContent.endsWith(ompBody(body) + "\n")).toBe(true);
}

test("every Claude agent has an omp counterpart with the mapped thinkingLevel, role, and body", () => {
	const sources = claudeAgentSources();
	expect(Object.keys(sources).sort()).toEqual([...ATLAS_AGENT_NAMES].sort());
	const generated = generatedAgents();
	expect(Object.keys(generated).sort()).toEqual([...ATLAS_AGENT_NAMES].sort());
	for (const [name, source] of Object.entries(sources)) expectAgentMatches(name, source, generated[name]);
});

function parseSource(source: string): { frontmatter: Record<string, unknown>; body: string } {
	const closeIndex = source.indexOf("\n---", 4);
	return {
		frontmatter: YAML.parse(source.slice(3, closeIndex)) as Record<string, unknown>,
		body: source.slice(closeIndex + 4).replace(/^\n/, ""),
	};
}

test("generated files carry the GENERATED header", () => {
	for (const content of Object.values(generatedAgents())) {
		expect(content).toContain("# GENERATED by omp/gen-agents.ts");
		expect(content).toContain("do not edit by hand");
	}
});

test("re-running the generator produces no diff against the committed output", () => {
	const before: Record<string, string> = generatedAgents();
	const { written } = generateAgents({ agentsDir, outDir });
	expect(written).toEqual([]);
	expect(generatedAgents()).toEqual(before);
});

test("renderGeneratedAgent YAML-safes descriptions and keeps the body verbatim", () => {
	const source = [
		"---",
		'name: "db-prober"',
		"description: \"Handles: colons, \\\"quotes\\\", and [brackets] fine.\"",
		"model: sonnet",
		"effort: low",
		"color: yellow",
		"---",
		"",
		"Body line one.",
		"Body line two with `code`.",
		"",
	].join("\n");
	const rendered = renderGeneratedAgent("db-prober.md", source);
	expect(rendered).not.toBeNull();
	const fm = frontmatterOf(rendered as string);
	expect(fm.name).toBe("db-prober");
	expect(fm.description).toBe("Handles: colons, \"quotes\", and [brackets] fine.");
	expect(fm.thinkingLevel).toBe(ATLAS_THINKING_LEVELS["db-prober"]);
	expect(fm.model).toEqual(modelPatternsFor("db-prober"));
	expect(rendered).toContain("Body line one.\nBody line two with `code`.");
});

test("unknown agent names are rejected instead of guessed", () => {
	const source = "---\nname: mystery-agent\ndescription: Not in the colony map.\n---\n\nBody.\n";
	expect(() => renderGeneratedAgent("mystery-agent.md", source)).toThrow("mystery-agent");
});

test("runner is registered on the mechanical tier: off thinking, @atlas-mechanic with @smol fallback", () => {
	expect(ATLAS_THINKING_LEVELS.runner).toBe("off");
	expect(roleFor("runner")).toBe("@atlas-mechanic");
	expect(modelPatternsFor("runner")).toEqual(["@atlas-mechanic", "haiku", "@smol"]);
	expect(ATLAS_AGENT_TARGETABLE.runner).toBe(true);
	const fm = frontmatterOf(generatedAgents().runner);
	expect(fm.thinkingLevel).toBe("off");
	expect(fm.model).toEqual(["@atlas-mechanic", "haiku", "@smol"]);
	expect(readFileSync(path.join(outDir, "runner.md"), "utf8")).toContain('thinkingLevel: "off"');
});

test("omp worker bodies carry no Claude-only tool vocabulary and instruct xd:// devices with real device names", () => {
	for (const [name, content] of Object.entries(generatedAgents())) {
		expect(content, name).not.toContain("ToolSearch");
		expect(content, name).not.toContain("SendMessage");
		expect(content, name).not.toMatch(/(?<!xd:\/\/)\bmcp__/);
		expect(content, name).toContain("xd://");
	}
	const explorer = generatedAgents().explorer;
	for (const device of [
		"xd://mcp__lean_ctx_ctx_compose",
		"xd://mcp__serena_find_symbol",
		"xd://mcp__context_mode_context_mode_ctx_batch_execute",
		"xd://mcp__claude_mem_mcp_search_search",
	]) {
		expect(explorer).toContain(device);
	}
	expect(explorer).not.toContain("mcp__plugin_");
});

test("ompBody refuses a body that would still carry a Claude-only token", () => {
	expect(() => ompBody("Call ToolSearch(\"x\") first.")).toThrow("ToolSearch");
	expect(() => ompBody("Use mcp__serena__find_symbol.")).toThrow("mcp__");
	expect(ompBody("Plain body.")).toBe("Plain body.");
});

test("read-only agents' omp definitions list no edit device; the writers still may", () => {
	const generated = generatedAgents();
	const editDevice = /xd:\/\/mcp__(serena_(replace_|insert_|rename_symbol|safe_delete)|lean_ctx_ctx_patch)/;
	for (const [name, content] of Object.entries(generated)) {
		if (["docs-curator", "implementer", "runner"].includes(name)) continue;
		expect(content, name).not.toMatch(editDevice);
	}
});

test("haiku-pinned agents run on the cheap mechanic role; implementer keeps the worker role at medium thinking", () => {
	for (const name of ["docs-auditor", "naming-glossary-audit", "schema-inventory", "runner"]) {
		expect(modelPatternsFor(name)).toEqual([ATLAS_MECHANIC_ROLE, ATLAS_TIER_DEFAULTS.mechanic, SMOL_FALLBACK_ROLE]);
	}
	expect(modelPatternsFor("explorer")).toEqual(["@atlas-worker", ATLAS_TIER_DEFAULTS.worker, SMOL_FALLBACK_ROLE]);
	expect(ATLAS_THINKING_LEVELS.implementer).toBe("medium");
	expect(roleFor("implementer")).toBe("@atlas-worker");
});
// ── omp-side resolution: the tier holds with no modelRoles.atlas-*, and a user-set role wins ──
// Uses omp's own resolver (src/config/model-resolver.ts resolveModelRoleValue :1421, resolveConfiguredModelPatterns :1246).
// before_subagent_spawn returns this list as `model` (types.ts BeforeSubagentSpawnEventResult :1301; structured-subagent.ts applySpawnHook :445-473 expands it with resolveConfiguredModelPatterns).
const OMP_RESOLVER = path.join(process.env.HOME ?? "", ".bun/install/global/node_modules/@oh-my-pi/pi-coding-agent/src/config/model-resolver.ts");
const mk = (provider: string, id: string) => ({ provider, id, name: id, api: "anthropic-messages" }) as never;
const MODELS = [mk("anthropic", "claude-opus-5-5"), mk("anthropic", "claude-sonnet-5-5"), mk("anthropic", "claude-haiku-4-5"), mk("openai", "gpt-5-mini")];
const resolveTier = async (agent: string, roles: Record<string, string>): Promise<string | undefined> => {
	const { resolveModelRoleValue } = await import(OMP_RESOLVER);
	const roleLookup = { getModelRole: (r: string) => roles[r] };
	return resolveModelRoleValue(modelPatternsFor(agent).join(","), MODELS, { roleLookup }).model?.id;
};

test.skipIf(!existsSync(OMP_RESOLVER))("no user modelRoles: runner->haiku, implementer->sonnet, verifier->@default else sonnet", async () => {
	expect(await resolveTier("runner", { default: "anthropic/claude-opus-5-5" })).toBe("claude-haiku-4-5");
	expect(await resolveTier("implementer", { default: "anthropic/claude-opus-5-5" })).toBe("claude-sonnet-5-5");
	expect(await resolveTier("verifier", { default: "anthropic/claude-opus-5-5" })).toBe("claude-opus-5-5");
	expect(await resolveTier("verifier", {})).toBe("claude-sonnet-5-5");
});

test.skipIf(!existsSync(OMP_RESOLVER))("a user-set modelRole overrides the default tier", async () => {
	expect(await resolveTier("runner", { "atlas-mechanic": "openai/gpt-5-mini" })).toBe("gpt-5-mini");
	expect(await resolveTier("implementer", { "atlas-worker": "anthropic/claude-opus-5-5" })).toBe("claude-opus-5-5");
	expect(await resolveTier("verifier", { "atlas-verifier": "openai/gpt-5-mini", default: "anthropic/claude-opus-5-5" })).toBe("gpt-5-mini");
});
