import { expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import * as path from "node:path";
import { YAML } from "bun";
import {
	ATLAS_AGENT_NAMES,
	ATLAS_AGENT_TARGETABLE,
	ATLAS_DEFAULT_FALLBACK_ROLE,
	ATLAS_MECHANIC_ROLE,
	ATLAS_THINKING_LEVELS,
	modelPatternsFor,
	roleFor,
	SMOL_FALLBACK_ROLE,
} from "./atlas-agents";
import { generateAgents, renderGeneratedAgent } from "./gen-agents";

const agentsDir = path.resolve(import.meta.dir, "..", "agents");
const outDir = path.resolve(import.meta.dir, "agents");

function claudeAgentSources(): Record<string, string> {
	const sources: Record<string, string> = {};
	for (const file of readdirSync(agentsDir).filter(file => file.endsWith(".md"))) {
		const content = readFileSync(path.join(agentsDir, file), "utf8");
		const name = YAML.parse(content.slice(content.indexOf("---") + 3, content.indexOf("\n---", 4))).name;
		sources[name] = content;
	}
	return sources;
}

function generatedAgents(): Record<string, string> {
	const files: Record<string, string> = {};
	for (const file of readdirSync(outDir).filter(file => file.endsWith(".md"))) {
		files[file.replace(/\.md$/, "")] = readFileSync(path.join(outDir, file), "utf8");
	}
	return files;
}

function frontmatterOf(content: string): Record<string, unknown> {
	return YAML.parse(content.slice(content.indexOf("---") + 3, content.indexOf("\n---", 4))) as Record<string, unknown>;
}

function expectedModelChain(name: string): string[] {
	if (name === "runner") return [ATLAS_MECHANIC_ROLE, SMOL_FALLBACK_ROLE];
	if (ATLAS_THINKING_LEVELS[name] === "medium") return [roleFor(name), ATLAS_DEFAULT_FALLBACK_ROLE, SMOL_FALLBACK_ROLE];
	return [roleFor(name), SMOL_FALLBACK_ROLE];
}

function expectAgentMatches(name: string, source: string, generatedContent: string): void {
	const { frontmatter, body } = parseSource(source);
	const fm = frontmatterOf(generatedContent);
	expect(fm.name).toBe(name);
	expect(fm.description).toBe(frontmatter.description);
	expect(fm.thinkingLevel).toBe(ATLAS_THINKING_LEVELS[name]);
	const model = fm.model as string[];
	expect(model[0]).toBe(roleFor(name));
	expect(model).toEqual(modelPatternsFor(name));
	expect(model).toEqual(expectedModelChain(name));
	expect(fm.spawns).toBe("none");
	expect(generatedContent.endsWith(body) || generatedContent.endsWith(body + "\n")).toBe(true);
}

test("every Claude agent has an omp counterpart with the mapped thinkingLevel, role, and body", () => {
	const sources = claudeAgentSources();
	expect(Object.keys(sources).sort()).toEqual([...ATLAS_AGENT_NAMES].sort());
	const generated = generatedAgents();
	expect(Object.keys(generated).sort()).toEqual([...ATLAS_AGENT_NAMES].sort());
	for (const [name, source] of Object.entries(sources)) expectAgentMatches(name, source, generated[name]);
});

function parseSource(source: string): { frontmatter: Record<string, unknown>; body: string } {
	const closeIndex = source.indexOf("\n---", 4);
	return {
		frontmatter: YAML.parse(source.slice(3, closeIndex)) as Record<string, unknown>,
		body: source.slice(closeIndex + 4).replace(/^\n/, ""),
	};
}

test("generated files carry the GENERATED header", () => {
	for (const content of Object.values(generatedAgents())) {
		expect(content).toContain("# GENERATED by omp/gen-agents.ts");
		expect(content).toContain("do not edit by hand");
	}
});

test("re-running the generator produces no diff against the committed output", () => {
	const before: Record<string, string> = generatedAgents();
	const { written } = generateAgents({ agentsDir, outDir });
	expect(written).toEqual([]);
	expect(generatedAgents()).toEqual(before);
});

test("renderGeneratedAgent YAML-safes descriptions and keeps the body verbatim", () => {
	const source = [
		"---",
		'name: "db-prober"',
		"description: \"Handles: colons, \\\"quotes\\\", and [brackets] fine.\"",
		"model: sonnet",
		"effort: low",
		"color: yellow",
		"---",
		"",
		"Body line one.",
		"Body line two with `code`.",
		"",
	].join("\n");
	const rendered = renderGeneratedAgent("db-prober.md", source);
	expect(rendered).not.toBeNull();
	const fm = frontmatterOf(rendered as string);
	expect(fm.name).toBe("db-prober");
	expect(fm.description).toBe("Handles: colons, \"quotes\", and [brackets] fine.");
	expect(fm.thinkingLevel).toBe(ATLAS_THINKING_LEVELS["db-prober"]);
	expect(fm.model).toEqual(modelPatternsFor("db-prober"));
	expect(rendered).toContain("Body line one.\nBody line two with `code`.");
});

test("unknown agent names are rejected instead of guessed", () => {
	const source = "---\nname: mystery-agent\ndescription: Not in the colony map.\n---\n\nBody.\n";
	expect(() => renderGeneratedAgent("mystery-agent.md", source)).toThrow("mystery-agent");
});

test("runner is registered on the mechanical tier: off thinking, @atlas-mechanic with @smol fallback", () => {
	expect(ATLAS_THINKING_LEVELS.runner).toBe("off");
	expect(roleFor("runner")).toBe("@atlas-mechanic");
	expect(modelPatternsFor("runner")).toEqual(["@atlas-mechanic", "@smol"]);
	expect(ATLAS_AGENT_TARGETABLE.runner).toBe(true);
	const fm = frontmatterOf(generatedAgents().runner);
	expect(fm.thinkingLevel).toBe("off");
	expect(fm.model).toEqual(["@atlas-mechanic", "@smol"]);
	expect(readFileSync(path.join(outDir, "runner.md"), "utf8")).toContain("thinkingLevel: off");
});