/**
 * Generates omp-native task-agent definitions from the Claude-format atlas
 * agent sources.
 *
 * Why: omp discards the frontmatter `model` of Claude-dialect plugin agents
 * (task/discovery.ts sets `ignoreModel` for plugins that declare the Claude
 * format, e.g. via `.claude-plugin/plugin.json`), so the copies under
 * `plugins/atlas/agents/` run on the session's default model. omp scans
 * `<extension-root>/agents` for extension packages and KEEPS `model` +
 * `thinkingLevel` there, and extension-package agents precede Claude plugin
 * agents in the first-wins-by-name merge — so generated omp-native copies in
 * this package override the model-less Claude copies of the same names.
 *
 * Usage (from any cwd): bun plugins/atlas/omp/gen-agents.ts
 * Reads   plugins/atlas/agents/*.md   (name, description, body)
 * Writes  plugins/atlas/omp/agents/<name>.md  (committed; idempotent)
 *
 * The parent re-runs this after the Claude-dialect agent bodies change.
 */
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import * as path from "node:path";
import { YAML } from "bun";
import { ATLAS_AGENT_NAMES, ATLAS_THINKING_LEVELS, modelPatternsFor, roleFor } from "./atlas-agents";
import { loadToolNames, translateToolNames } from "./style";

export interface GenerateOptions {
	/** Directory containing Claude-format atlas agent `*.md` sources. */
	agentsDir: string;
	/** Directory receiving generated omp-native agent `*.md` files. */
	outDir: string;
}

const HEADER = (sourceFile: string) => [
	"# GENERATED by omp/gen-agents.ts from agents/" + sourceFile + " — do not edit by hand.",
	"# Re-generate with: bun plugins/atlas/omp/gen-agents.ts (idempotent; commit the output).",
];

/** Claude-only tool vocabulary that must not survive into an omp worker prompt (omp has no ToolSearch, SendMessage or `mcp__` names). */
const CLAUDE_ONLY_TOKENS = /ToolSearch|SendMessage|(?<!xd:\/\/)\bmcp__/;

/** The ToolSearch intro paragraph (both phrasings) with its `select:` list, plus the optional re-search line that follows. */
const TOOL_LOAD_BLOCK =
	/(?:Deferred MCP tools are absent|Load your tools first)[^\n]*\n\n[ \t]+ToolSearch\("select:([^"]*)"\)\n(?:\nIf a tool never appears[^\n]*\n)?/;

/**
 * Rewrites a Claude-dialect worker body for omp: the ToolSearch batch becomes the matching `xd://` devices
 * (derived from the same list, through the shared contracts/tool-names.json mint), SendMessage becomes an IRC
 * `write agent://`, and the report container is pointed at the structured `yield` result. Throws when a Claude-only
 * token survives, so a new agent body cannot silently ship a prompt omp cannot follow.
 */
export function ompBody(body: string): string {
	const map = loadToolNames();
	if (!map) throw new Error("contracts/tool-names.json is unreadable: cannot translate agent bodies for omp");
	const out = body
		.replace(TOOL_LOAD_BLOCK, (_m, list: string) => {
			const devices = translateToolNames(list.replace(/mcp__plugin_/g, "mcp__"), map).split(",");
			return [
				"Every MCP tool below is an `xd://` device: call it with `write`, `path` = the device, `content` = its JSON args (e.g. `write path=xd://mcp__lean_ctx_ctx_search content={\"pattern\":\"...\"}`). Read `xd://<device>` once for its schema before the first call. Your devices (a missing one costs nothing; skip it):",
				"",
				...devices.map(device => "    " + device),
				"",
				"Do not probe devices one by one mid-task - that is how runs fall back to noisy `Grep`/`Bash`.",
				"",
			].join("\n");
		})
		.replace(/\bmcp__cmux-browser__[a-z_]+/g, name => translateToolNames(name, map))
		.replace(/SendMessage that sibling by name/g, "`write agent://<name>` to that sibling")
		.replace(/On Claude Code use SendMessage to the lead by name\. On omp use `write`/g, "Use `write`")
		.replace(/the ToolSearch call above exists/g, "the xd:// devices above exist")
		.replace(/Load deferred\/MCP tool schemas \(`ToolSearch`\) before calling them\./g, "Read an `xd://<device>` schema before the first call.")
		.replace(/Load deferred\/MCP tool schemas before calling them\*\* \(`ToolSearch` to fetch the schema\)/g, "Read an `xd://<device>` schema before the first call**")
		.replace(/`activate_project`/g, "`xd://mcp__serena_activate_project`")
		.replace(
			/(Your final message is exactly the container below[^\n]*\n)/g,
			"$1On omp, return these same fields through `yield` as the structured result (`status`, `stepsDone`, `stepsTotal`, `filesChanged`, `evidence[{step, command, output}]`, `deliverable`, `next`); do not write the container as prose.\n",
		);
	const leftover = CLAUDE_ONLY_TOKENS.exec(out);
	if (leftover) throw new Error("omp agent body still carries Claude-only token '" + leftover[0] + "'");
	return out;
}

/** Split an agent markdown file into its frontmatter map and verbatim body. */
function parseAgentMarkdown(content: string): { frontmatter: Record<string, unknown>; body: string } {
	const trimmed = content.replace(/^\uFEFF/, "");
	if (!trimmed.startsWith("---")) throw new Error("agent file has no frontmatter");
	const closeIndex = trimmed.indexOf("\n---", 3);
	if (closeIndex < 0) throw new Error("agent file frontmatter is not closed");
	const frontmatter = YAML.parse(trimmed.slice(3, closeIndex)) as Record<string, unknown>;
	if (!frontmatter || typeof frontmatter !== "object") throw new Error("agent frontmatter did not parse to a map");
	const afterClose = trimmed.slice(closeIndex + 4);
	const body = afterClose.startsWith("\n") ? afterClose.slice(1) : afterClose;
	return { frontmatter, body };
}

/** Render one generated agent file for a parsed source agent. */
export function renderGeneratedAgent(sourceFile: string, content: string): string | null {
	const { frontmatter, body } = parseAgentMarkdown(content);
	const name = frontmatter.name;
	const description = frontmatter.description;
	if (typeof name !== "string" || !name.trim() || typeof description !== "string" || !description.trim()) {
		return null;
	}
	const thinkingLevel = ATLAS_THINKING_LEVELS[name];
	if (!thinkingLevel) {
		throw new Error("no thinkingLevel mapping for atlas agent " + name);
	}
	// JSON.stringify output is valid YAML (double-quoted scalar), so
	// descriptions containing colons/quotes stay safe without a YAML emitter.
	const lines = [
		"---",
		...HEADER(sourceFile),
		`name: ${JSON.stringify(name)}`,
		`description: ${JSON.stringify(description)}`,
		`thinkingLevel: ${JSON.stringify(thinkingLevel)}`,
		`model: ${JSON.stringify(modelPatternsFor(name))}`,
		"# Lead-only dispatch: atlas workers must not spawn subagents.",
		`spawns: ${JSON.stringify("none")}`,
		"---",
		"",
		ompBody(body),
	];
	return lines.join("\n").replace(/\n*$/, "\n");
}

/**
 * Generate every omp-native agent file. Writes only when the rendered bytes
 * differ from what is on disk, so re-running produces no diff.
 */
export function generateAgents({ agentsDir, outDir }: GenerateOptions): { written: string[] } {
	const sources = readdirSync(agentsDir)
		.filter(file => file.endsWith(".md"))
		.sort();
	const written: string[] = [];
	for (const sourceFile of sources) {
		const rendered = renderGeneratedAgent(sourceFile, readFileSync(path.join(agentsDir, sourceFile), "utf8"));
		if (rendered === null) continue;
		if (!statSync(outDir, { throwIfNoEntry: false })) mkdirSync(outDir, { recursive: true });
		const outPath = path.join(outDir, sourceFile);
		const existing = statSync(outPath, { throwIfNoEntry: false })
			? readFileSync(outPath, "utf8")
			: undefined;
		if (existing !== rendered) {
			writeFileSync(outPath, rendered);
			written.push(path.basename(sourceFile));
		}
	}
	return { written };
}

function main(): void {
	const agentsDir = path.resolve(import.meta.dir, "..", "agents");
	const outDir = path.resolve(import.meta.dir, "agents");
	const { written } = generateAgents({ agentsDir, outDir });
	if (written.length > 0) {
		console.log(`generated ${written.length} omp agent file(s): ${written.join(", ")}`);
	} else {
		console.log(`omp agent files up to date (${readdirSync(outDir).filter(f => f.endsWith(".md")).length} files)`);
	}
}

if (import.meta.main) main();

// Re-exported for tests and tooling that need the shared maps without
// importing the generator's side-effectful module graph.
export { ATLAS_AGENT_NAMES, ATLAS_THINKING_LEVELS, modelPatternsFor, roleFor };