import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { chromium } from "playwright-core";
import panes from "../site/demo/fixtures/panes.json";

// Build the unmodified app and inject only the demo's fixture transport. All files and
// HTTP traffic stay in this disposable, loopback-only app; no herdr session is opened.
const repo = join(import.meta.dir, "..");
const app = mkdtempSync(join(tmpdir(), "herdr-droplet-demo-"));
try {
  const build = Bun.spawnSync([join(repo, "node_modules/.bin/vite"), "build", "--base", "./", "--outDir", app, "--emptyOutDir", "--logLevel", "warn"], { cwd: repo });
  assert.equal(build.exitCode, 0, new TextDecoder().decode(build.stderr));
  const transport = await Bun.build({
    entrypoints: [join(repo, "site/demo/transport.ts")], outdir: app,
    naming: "demo-transport.js", target: "browser",
    define: { __APP_VERSION__: JSON.stringify(JSON.parse(readFileSync(join(repo, "package.json"), "utf8")).version) },
  });
  assert.ok(transport.success, transport.logs.map(String).join("\n"));
  const index = join(app, "index.html");
  const html = readFileSync(index, "utf8");
  assert.match(html, /<script type="module"/);
  writeFileSync(index, html.replace(/<script type="module"/, '<script src="./demo-transport.js"></script>\n    <script type="module"'));

  const server = Bun.serve({ hostname: "127.0.0.1", port: 0, async fetch(request) {
    const path = new URL(request.url).pathname;
    if (!path.startsWith("/herdr-web-ui/demo/app/")) return new Response("not found", { status: 404 });
    let file: string;
    try { file = decodeURIComponent(path.slice("/herdr-web-ui/demo/app/".length)); }
    catch { return new Response("bad path", { status: 400 }); }
    if (!file || file.endsWith("/")) file += "index.html";
    if (file.split("/").includes("..") || file.includes("\\")) return new Response("bad path", { status: 400 });
    const body = Bun.file(join(app, file));
    if (!(await body.exists())) return new Response("not found", { status: 404 });
    // Chromium on Linux has no native phone safe-area inset. Mock the CSS environment
    // only; geometry and hit testing still use the real rendered app and real card.
    if (file.endsWith(".css")) return new Response((await body.text()).replace(/env\(safe-area-inset-top(?:,\s*0px)?\)/g, "59px"), { headers: { "content-type": "text/css" } });
    return new Response(body);
  } });
  try {
    const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? "/opt/google/chrome/chrome", headless: true, args: ["--no-sandbox"] });
    try {
      const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: "en-US" });
      try {
        await context.addInitScript(() => {
          localStorage.setItem("herdr-web-ui:settings", JSON.stringify({ language: "en", alertDone: "always" }));
          const viewport = window.visualViewport!;
          let height = 795;
          Object.defineProperty(viewport, "height", { get: () => height });
          (window as Window & { dropletViewport: (value: number) => void }).dropletViewport = (value) => {
            height = value;
            viewport.dispatchEvent(new Event("resize"));
          };
        });
        const page = await context.newPage();
        const errors: string[] = [];
        page.on("pageerror", (error) => errors.push(error.message));
        // Let the demo's unrelated startup completion occur while its own pane is
        // selected, so it cannot replace the alert generated by this scenario.
        await page.goto(`http://127.0.0.1:${server.port}/herdr-web-ui/demo/app/?pane=${encodeURIComponent(panes.api)}`);
        await page.locator(".conn-live").waitFor();
        await page.locator(`.pane-item:has(.pane-select[title^="${panes.api} —"]) [data-status="done"]`).first().waitFor({ state: "attached", timeout: 8_000 });
        await page.getByTitle("Chat transcript (⌘⇧J)", { exact: true }).click();
        const message = page.getByRole("textbox", { name: "Message", exact: true });
        await message.fill("Demo geometry check");
        await page.getByRole("button", { name: "Send message", exact: true }).click();
        await page.locator(`.pane-item:has(.pane-select[title^="${panes.api} —"]) [data-status="working"]`).first().waitFor({ state: "attached", timeout: 5_000 });
        // Mobile drawer rows can be offscreen; dispatch the same row click while the
        // demo's delayed answer is in flight, without reloading its fixture state.
        await page.locator(`.pane-select[title^="${panes.docs} —"]`).evaluate((row: HTMLElement) => row.click());
        await page.locator(`.pane-select[title^="${panes.docs} —"][aria-current="true"]`).waitFor({ state: "attached" });
        const card = page.locator(".droplet-card");
        await card.waitFor({ state: "visible", timeout: 6_000 });
        assert.match(await card.getAttribute("aria-label") ?? "", /Finished/);
        assert.equal(await page.locator(".droplet").getAttribute("data-kind"), "done");

        const check = async (label: string) => {
          await page.waitForFunction(() => {
            const card = document.querySelector(".droplet-card")!;
            return getComputedStyle(card).opacity === "1";
          });
          // From 769px the header is 46px, so a rotation changes its height: the card follows on
          // the header's next resize callback. Give it a bounded wait; the assertion below still
          // decides, and reports the numbers.
          await page.waitForFunction(() => {
            const top = document.querySelector(".droplet-card")!.getBoundingClientRect().top;
            const header = document.querySelector(".app-header")!.getBoundingClientRect().bottom;
            const safe = parseFloat(getComputedStyle(document.querySelector(".droplet-probe")!).paddingTop) || 0;
            return Math.abs(top - (Math.max(safe, header) + 12)) <= 2;
          }, undefined, { timeout: 5_000 }).catch(() => undefined);
          const geometry = await page.evaluate(() => {
            const card = document.querySelector<HTMLElement>(".droplet-card")!;
            const rect = card.getBoundingClientRect();
            const header = document.querySelector(".app-header")!.getBoundingClientRect();
            const safe = parseFloat(getComputedStyle(document.querySelector(".droplet-probe")!).paddingTop) || 0;
            const hit = document.elementFromPoint(rect.left + rect.width / 2, rect.top + rect.height / 2);
            return { top: rect.top, left: rect.left, right: rect.right, width: innerWidth, bottom: rect.bottom,
              headerBottom: header.bottom, safe, hit: hit === card || card.contains(hit),
              phase: document.querySelector(".droplet")?.getAttribute("data-phase") };
          });
          assert.equal(geometry.phase, "in", `${label}: card still interactive`);
          assert.ok(geometry.safe > 0, `${label}: mocked safe inset reached app CSS`);
          assert.ok(Math.abs(geometry.top - (Math.max(geometry.safe, geometry.headerBottom) + 12)) <= 2,
            `${label}: card top ${geometry.top}, header ${geometry.headerBottom}, safe ${geometry.safe}`);
          assert.ok(geometry.left >= 0 && geometry.right <= geometry.width, `${label}: horizontal bounds ${JSON.stringify(geometry)}`);
          assert.ok(geometry.hit, `${label}: card center receives pointer events`);
          console.log(`PASS ${label}: rendered card clears header and inset and is hit-testable`);
        };
        await check("portrait, keyboard inactive");
        await message.focus();
        await page.evaluate(() => (window as Window & { dropletViewport: (value: number) => void }).dropletViewport(480));
        await page.locator("html[data-keyboard]").waitFor();
        await check("portrait, keyboard visible");
        await page.evaluate(() => (window as Window & { dropletViewport: (value: number) => void }).dropletViewport(795));
        await page.locator("html[data-keyboard]").waitFor({ state: "detached" });
        await page.setViewportSize({ width: 844, height: 390 });
        await check("landscape, keyboard inactive");
        await card.tap();
        await page.locator(`.pane-select[title^="${panes.api} —"][aria-current="true"]`).waitFor({ state: "attached" });
        await page.locator(".droplet").waitFor({ state: "detached" });
        await page.setViewportSize({ width: 390, height: 844 });
        await message.fill("Demo keyboard tap check");
        await page.getByRole("button", { name: "Send message", exact: true }).click();
        await page.locator(`.pane-item:has(.pane-select[title^="${panes.api} —"]) [data-status="working"]`).first().waitFor({ state: "attached" });
        await page.locator(`.pane-select[title^="${panes.docs} —"]`).evaluate((row: HTMLElement) => row.click());
        await page.locator(`.pane-select[title^="${panes.docs} —"][aria-current="true"]`).waitFor({ state: "attached" });
        await page.getByRole("textbox", { name: "Message", exact: true }).focus();
        await page.evaluate(() => (window as Window & { dropletViewport: (value: number) => void }).dropletViewport(480));
        await page.locator("html[data-keyboard]").waitFor();
        await card.waitFor({ state: "visible", timeout: 6_000 });
        await check("portrait, keyboard visible, second alert");
        await card.tap();
        await page.locator(`.pane-select[title^="${panes.api} —"][aria-current="true"]`).waitFor({ state: "attached" });
        await page.locator(".droplet").waitFor({ state: "detached" });
        assert.deepEqual(errors, []);
        console.log("PASS card tap closes the alert and opens its demo pane with keyboard inactive and visible");
      } finally { await context.close(); }
    } finally { await browser.close(); }
  } finally { server.stop(); }
} finally { rmSync(app, { recursive: true, force: true }); }
