// Atlas mod sprite set: db-prober.
// Hand-drawn pixel grids; '.' = transparent. Palette keys: v visor, s suit, h helmet/drill
// casing, p prop (DB cylinder), r rim, a accent, w white, k dark, e eyes, i amber, f fail-red,
// g ghost-grey.
import type { SpriteSet } from '../contract';

const palette: Record<string, string> = {
  v: '#9fb0b8',
  s: '#121a1e',
  h: '#f5c531',
  p: '#7f8f96',
  r: '#0c1215',
  a: '#b5a3fa',
  w: '#e6edf0',
  k: '#060a0c',
  e: '#0c1215',
  i: '#f2aa40',
  f: '#ff7570',
  g: '#93a4ac',
};

const portrait: SpriteSet['portrait'] = {
  idle: [
    [
      '................',
      '....hhhhhhhh....',
      '...hhhhhhhhhh...',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssspp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '................',
      '....hhhhhhhh....',
      '...hhhhhhhhhh...',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssppp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
  working: [
    [
      '................',
      '....hhhhhhhh.hh.',
      '...hhhhhhhhhhpp.',
      '..hhhhhhhhhhhh.p',
      '..hhvvvvvvvvhh.p',
      '..hhvveevveehh.p',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..ssssssssssss..',
      '..ssssssssssss..',
      '..ssssssssssss..',
      '..ssssssssssss..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '................',
      '....hhhhhhhh....',
      '...hhhhhhhhhh...',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..ssssssssssss..',
      '..sssssssssspp..',
      '..sssssssspphh..',
      '..ssssssssssih..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
  spawn: [
    [
      '.......aa.......',
      '....hhhhaahhh...',
      '...hhhhhhaahh...',
      '..hhhhhhhaahhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssspp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '......aaaa......',
      '....hhaaaahh....',
      '...hhhaaaahhh...',
      '..hhhhaaaahhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssspp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
  input: [
    [
      '................',
      '....hhhhhhhh..i.',
      '...hhhhhhhhhh.i.',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvh.i.',
      '.shhvveevveehh..',
      '.shhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssspp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '................',
      '....hhhhhhhh.i..',
      '...hhhhhhhhhh.i.',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvh..i',
      'shhvveevveehh...',
      '.hhvvvvvvvvhh...',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssppp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
  done: [
    [
      '................',
      '....hhhhhhhh...v',
      '...hhhhhhhhhh...',
      'v.hhhhhhhhhhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh.s',
      '..hhvvvvvvvvhh.s',
      '..hhhhhhhhhhhsss',
      '...rrrrrrrrrr...',
      '..sssssssssspp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '................',
      '...hhhhhhhhhh..v',
      'v.hhhhhhhhhhhh..',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh.s',
      '..hhvvvvvvvvhhss',
      '..hhhhhhhhhhhsss',
      '...rrrrrrrrrr...',
      '..sssssssssppp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
  failed: [
    [
      '................',
      '..f.hhhhhhhh....',
      '...hhhhhhhhhh...',
      '..hhhhhhhhhhhh..',
      '..hhvfvvvvfvhh..',
      '..hhvvfvfvvvhh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhhf.',
      '...rrrrrrrrrr...',
      '..sssssssssspp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '................',
      '....hhhhhhhh....',
      '..fhhhhhhhhhh...',
      '..hhhhhhhhhhhh..',
      '..hhvfvvvvfvhh..',
      '..hhfvveevvfhh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssppp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
  stuck: [
    [
      '................',
      '....hhhhhhhh.ww.',
      '...hhhhhhhhhh.w.',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssspp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '..............w.',
      '....hhhhhhhh.w..',
      '...hhhhhhhhhhww.',
      '..hhhhhhhhhhhh..',
      '..hhvvvvvvvvhh..',
      '..hhvveevveehh..',
      '..hhvvvvvvvvhh..',
      '..hhhhhhhhhhhh..',
      '...rrrrrrrrrr...',
      '..sssssssssppp..',
      '..ssssssssspppp.',
      '..ssssssssspprp.',
      '..sssssssssspp..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
  killed: [
    [
      '................',
      '....gggggggg....',
      '...gggggggggg...',
      '..gggggggggggg..',
      '..ggwwggggwwgg..',
      '..ggwwggggwwgg..',
      '..gggggggggggg..',
      '..gggggggggggg..',
      '...gggggggggg...',
      '..gggggggggggg..',
      '..gggggggggggg..',
      '..g.gg..g.gg....',
      '..ssssssssssss..',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
    [
      '................',
      '....hhhhhhhh....',
      '....gggggggg....',
      '...gggggggggg...',
      '..gggggggggggg..',
      '..ggwwggggwwgg..',
      '..gggggggggggg..',
      '..gggggggggggg..',
      '..gggggggggggg..',
      '...gggggggggg...',
      '..gggggggggggg..',
      '..gggggggggggg..',
      '..g.gg..g.gg....',
      '...sss....sss...',
      '...kkk....kkk...',
      '................',
    ],
  ],
};

const field: SpriteSet['field'] = {
  idle: [
    [
      '........',
      '..hhhh..',
      '.hhhhhh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaaspp',
      '..s..ppp',
      '..k..pp.',
    ],
    [
      '........',
      '..hhhh..',
      '.hhhhhh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaass.',
      '..s..ppp',
      '..k..ppp',
    ],
  ],
  working: [
    [
      '........',
      '..hhhh..',
      '.hhhhhh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaassp',
      '..s..phh',
      '..k...hh',
    ],
    [
      '........',
      '..hhhh..',
      '.hhhhhh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaass.',
      '..s..phh',
      '..k..hhh',
    ],
  ],
  spawn: [
    [
      '...aa...',
      '..haah..',
      '.hhaahh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaaspp',
      '..s..ppp',
      '..k..pp.',
    ],
    [
      '..aaaa..',
      '.haaah..',
      'hhaaahh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaass.',
      '..s..pp.',
      '..k..ppp',
    ],
  ],
  input: [
    [
      '........',
      '..hhhh.i',
      '.hhhhhhi',
      '.hvvvvh.',
      '.hveevh.',
      'shvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaaspp',
      '..s..ppp',
      '..k..pp.',
    ],
    [
      '........',
      '..hhhh.i',
      '.hhhhhhi',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaass.',
      '..s..ppp',
      '..k..ppp',
    ],
  ],
  done: [
    [
      '........',
      '..hhhhv.',
      '.hhhhhh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhss',
      '..rrrss.',
      '.ssssss.',
      '.ssaaspp',
      '..s..ppp',
      '..k..pp.',
    ],
    [
      '........',
      '..hhhh.v',
      '.hhhhhh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      'hhhhhhss',
      '..rrrr..',
      '.ssssss.',
      '.ssaass.',
      '..s..ppp',
      '..k..ppp',
    ],
  ],
  failed: [
    [
      '........',
      '..fhhh..',
      '.hhhhhh.',
      '.hvvvvh.',
      '.hfvevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrrf.',
      '.ssssss.',
      '.ssaaspp',
      '..s..ppp',
      '..k..pp.',
    ],
    [
      '........',
      '..hhhh..',
      '.fhhhh..',
      '.hvvvvh.',
      '.hvefvh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaass.',
      '..s..pp.',
      '..k..ppp',
    ],
  ],
  stuck: [
    [
      '........',
      '..hhhh.w',
      '.hhhhhhw',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaaspp',
      '..s..ppp',
      '..k..pp.',
    ],
    [
      '........',
      '..hhhh.w',
      '.hhhhhh.',
      '.hvvvhw.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..rrrr..',
      '.ssssss.',
      '.ssaass.',
      '..s..pp.',
      '..k..ppp',
    ],
  ],
  killed: [
    [
      '........',
      '..gggg..',
      '.gggggg.',
      '.gwggwg.',
      '.gwggwg.',
      '.gggggg.',
      '.gggggg.',
      '..gggg..',
      '.gggggg.',
      '.gggggg.',
      '.g.gg.g.',
      '........',
    ],
    [
      '........',
      '........',
      '..gggg..',
      '.gwggwg.',
      '.gggggg.',
      '.gggggg.',
      '.gggggg.',
      '.gggggg.',
      '..gggg..',
      '.gggggg.',
      '.gggggg.',
      '.g.gg.g.',
    ],
  ],
};

const mini: SpriteSet['mini'] = {
  idle: [
    ['hhhh', 'hvvh', 'hhhh', 'spp.'],
    ['hhhh', 'hvvh', 'hhhh', '.pp.'],
  ],
  working: [
    ['hhhh', 'hvvh', 'hhph', 'spp.'],
    ['hhhh', 'hvvh', 'hhhh', 'hhh.'],
  ],
  spawn: [
    ['aaaa', 'hvvh', 'hhhh', 'spp.'],
    ['.aaa', 'hvvh', 'hhhh', '.pp.'],
  ],
  input: [
    ['hhhh', 'hvvh', 'hiih', 'spp.'],
    ['hhhh', 'hihh', 'hhhh', '.pp.'],
  ],
  done: [
    ['vhhh', 'hvvh', 'hhhh', 'spp.'],
    ['hhhh', 'hvvh', 'hhhh', 'sppv'],
  ],
  failed: [
    ['hhhh', 'hfvh', 'hhhh', 'spp.'],
    ['hhhh', 'hfvf', 'hhhh', 'spp.'],
  ],
  stuck: [
    ['hhhh', 'hvvh', 'hhhh', 'spww'],
    ['hhhh', 'hvvh', 'hhhh', 'ppw.'],
  ],
  killed: [
    ['gggg', 'gwgg', 'gggg', 'g..g'],
    ['hhhh', 'ggwg', 'hhhh', '.g.g'],
  ],
};

export default { persona: 'db-prober', palette, portrait, field, mini } satisfies SpriteSet;
