// Atlas mod sprite set: ui-tester.
// Hand-drawn pixel grids; '.' = transparent. Palette keys: v visor (screen), s suit (window
// sill), h helmet (window chrome), p prop (toolbar), r rim (divider), a accent, w white
// (buttons/sweat), k dark, e eyes, i amber (cursor), f fail-red, g ghost-grey.
import type { SpriteSet } from '../contract';

const palette: Record<string, string> = {
  v: '#e8f4fb',
  s: '#121a1e',
  h: '#ff7ac2',
  p: '#b9c7cf',
  r: '#0c1215',
  a: '#b5a3fa',
  w: '#e6edf0',
  k: '#060a0c',
  e: '#0c1215',
  i: '#f2aa40',
  f: '#ff7570',
  g: '#93a4ac',
};

const portrait: SpriteSet['portrait'] = {
  idle: [
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
    ],
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvhi..',
      '..hvvvvvvvvvvi..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
    ],
  ],
  working: [
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvii..',
      '..ssssssssssii..',
      '...gggg....gg...',
      '................',
      '................',
    ],
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvviih..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
    ],
  ],
  spawn: [
    [
      '................',
      '..hhhhhhhaahhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
    ],
    [
      '................',
      '..hhhaaaahhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
    ],
  ],
  input: [
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvivh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvii..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
    ],
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvih..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
    ],
  ],
  done: [
    [
      '..............v.',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvii..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
    ],
    [
      '.v..............',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssii..',
      '...gggg....gg...',
      '................',
    ],
  ],
  failed: [
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvhf.',
      '..hvvvvvvvvvvh..',
      '..hfvveevveevh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
    ],
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..f.hvvvvvvvvvh.',
      '..hvvvvvvvvvvh..',
      '..hvvfvfvfvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
    ],
  ],
  stuck: [
    [
      '................',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
    ],
    [
      '..............w.',
      '..hhhhhhhhhhhh..',
      '..hppwwwwwwpph..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvveevveevvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hrrrrrrrrrrh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hvvvvvvvvvvh..',
      '..hkkkkkkkkkkh..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
    ],
  ],
  killed: [
    [
      '................',
      '..gggggggggggg..',
      '..gppwwwwwwppg..',
      '..gwvvvvvvvvwg..',
      '..gwvvvvvvvvwg..',
      '..gwveevveevwg..',
      '..gwvvvvvvvvwg..',
      '..gwvvvvvvvvwg..',
      '..grrrrrrrrrrg..',
      '..gwvvvvvvvvwg..',
      '..gwvvvvvvvvwg..',
      '..gkkkkkkkkkkg..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
    ],
    [
      '................',
      '................',
      '..gggggggggggg..',
      '..gppwwwwwwppg..',
      '..gwvvvvvvvvwg..',
      '..gwvvvvvvvvwg..',
      '..gwveevveevwg..',
      '..gwvvvvvvvvwg..',
      '..grrrrrrrrrrg..',
      '..gwvvvvvvvvwg..',
      '..gkkkkkkkkkkg..',
      '..ssssssssssss..',
      '...gggg....gg...',
      '................',
      '................',
      '................',
    ],
  ],
};

const field: SpriteSet['field'] = {
  idle: [
    [
      '........',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '........',
      '..hhhh..',
      '.hppwwh.',
      '.hvvivh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
  working: [
    [
      '........',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhii.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '........',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvih.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
  spawn: [
    [
      '...aa...',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '..aaaa..',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
  input: [
    [
      '........',
      '..hhhh..',
      '.hppwwh.',
      '.hvvivh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '........',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
  done: [
    [
      '......v.',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '.v......',
      '..hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
  failed: [
    [
      '........',
      '..hhhh..',
      '.hppwwh.',
      '.hfvevh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '........',
      '..hhhh..',
      '.fppwwh.',
      '.hvvvvh.',
      '.hvefvh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
  stuck: [
    [
      '........',
      '..hhhh.w',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '........',
      'w.hhhh..',
      '.hppwwh.',
      '.hvvvvh.',
      '.hveevh.',
      '.hvvvvh.',
      '.hhhhhh.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
  killed: [
    [
      '........',
      '..gggg..',
      '.gppwwg.',
      '.gwvvwg.',
      '.gveevg.',
      '.gwvvwg.',
      '.gggggg.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
    [
      '........',
      '........',
      '..gggg..',
      '.gppwwg.',
      '.gwvvwg.',
      '.gveevg.',
      '.gggggg.',
      '..kkkk..',
      '.ssssss.',
      '..gggg..',
      '...gg...',
      '........',
    ],
  ],
};

const mini: SpriteSet['mini'] = {
  idle: [
    ['hhhh', 'hvvh', 'heeh', 'kkkk'],
    ['hhhh', 'hvvh', 'heih', 'kkkk'],
  ],
  working: [
    ['hhhh', 'hvvh', 'hiii', 'kkkk'],
    ['hhhh', 'hvih', 'heeh', 'kkkk'],
  ],
  spawn: [
    ['aaaa', 'hvvh', 'heeh', 'kkkk'],
    ['.aaa', 'hvvh', 'heeh', 'kkkk'],
  ],
  input: [
    ['hhhh', 'hvih', 'heeh', 'kkkk'],
    ['hhhh', 'hvvh', 'hieh', 'kkkk'],
  ],
  done: [
    ['vhhh', 'hvvh', 'heeh', 'kkkk'],
    ['hhhh', 'hvvh', 'heeh', 'kkvv'],
  ],
  failed: [
    ['hhhh', 'hfvh', 'heeh', 'kkkk'],
    ['hhhh', 'hfvf', 'heeh', 'kkkk'],
  ],
  stuck: [
    ['hhhh', 'hvwh', 'heeh', 'kkkk'],
    ['whhh', 'hvvh', 'heeh', 'kkkk'],
  ],
  killed: [
    ['gggg', 'gwgg', 'gggg', 'kkkk'],
    ['gggg', 'gggg', 'gwgg', '.kkk'],
  ],
};

export default { persona: 'ui-tester', palette, portrait, field, mini } satisfies SpriteSet;
